/**
 * @file
 * @brief Public C API for Viture Glasses device provider lifecycle and management.
 * @copyright 2025 VITURE Inc. All rights reserved.
 *
 * This header defines the core public C API for XR device provider instances:
 * - Lifecycle management: create, initialize, start, stop, shutdown, destroy
 * - Callback registration: state change callbacks and log hooks
 * - Device information: device type, product ID validation, market name
 * - Utility functions: thread ID retrieval, log level management
 *
 * For device control functions (display mode, brightness, volume, etc.),
 * see viture_protocol_public.h.
 */

#ifndef VITURE_GLASSES_PROVIDER_H
#define VITURE_GLASSES_PROVIDER_H

#include "viture_macros_public.h"

/**
 * @brief Handle type for XRDeviceProvider instances. This is an opaque pointer
 * returned by `xr_device_provider_create` and consumed by other API calls.
 */
typedef void* XRDeviceProviderHandle;

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Callback for reporting glass state changes (brightness, volume, display mode, etc.)
 *
 * See `VITURE_CALLBACK_ID_*` constants in viture_protocol_public.h for detailed id and values
 *
 * @param glass_state_id  Identifier for the state being reported.
 * @param glass_value     Integer value associated with the state.
 */
typedef void (*GlassStateCallback)(int glass_state_id, int glass_value);

/**
 * @brief Log hook function type
 *
 * This callback is invoked for each log message generated by the library.
 * It allows external applications to capture, filter, or redirect log messages
 * to custom logging systems (files, remote servers, crash reporting, etc.).
 *
 * @param level Log level (0: None, 1: Error, 2: Info, 3: Debug)
 * @param tag Log tag (typically "libglasses")
 * @param message Log message content
 */
typedef void (*LogHook)(int level, const char* tag, const char* message);

/**
 * @brief Device types supported by the SDK.
 *
 * Use these values to determine device-specific behavior after creating an
 * `XRDeviceProvider` instance, e.g. registering callbacks.
 */
typedef enum {
    XR_DEVICE_TYPE_VITURE_GEN1 = 0,
    XR_DEVICE_TYPE_VITURE_GEN2 = 1,
    XR_DEVICE_TYPE_VITURE_CARINA = 2
} XRDeviceType;

#ifdef __ANDROID__
/**
 * @brief Android variant: Create an XRDeviceProvider instance
 *
 * Due to Android restrictions, detailed usb information is needed for creation
 *
 * @param product_id Product ID of the opened usb device
 * @param file_descriptor File descriptor of the opened usb device
 * @return Handle to the created instance, or NULL on failure
 */
VITURE_API XRDeviceProviderHandle xr_device_provider_create(int product_id,
                                                            int file_descriptor);
#else
/**
 * @brief Non-Android variant: Create an XRDeviceProvider instance
 *
 * The non-Android signature accepts only `product_id`
 *
 * @param product_id Product ID of the opened usb device
 * @return Handle to the created instance, or NULL on failure
 */
VITURE_API XRDeviceProviderHandle xr_device_provider_create(int product_id);
#endif

/**
 * @brief Initialize the XRDeviceProvider
 * @param handle Handle to the XRDeviceProvider instance
 * @param custom_config Optional custom configuration string (can be NULL)
 * @param cache_file_dir Optional directory path for caching data (can be NULL).
 * @return 0: Success, -1: Param error, -2: Calibration init error, -3: Serial number fetch error, -4: Other error
 */
VITURE_API int xr_device_provider_initialize(XRDeviceProviderHandle handle,
                                             const char* custom_config,
                                             const char* cache_file_dir);

/**
 * @brief Start the XRDeviceProvider
 * @param handle Handle to the XRDeviceProvider instance
 * @return 0: Success, -1: Param error, -2: Other error
 */
VITURE_API int xr_device_provider_start(XRDeviceProviderHandle handle);

/**
 * @brief Stop the XRDeviceProvider
 * @param handle Handle to the XRDeviceProvider instance
 * @return 0: Success, -1: Param error, -2: Other error
 */
VITURE_API int xr_device_provider_stop(XRDeviceProviderHandle handle);

/**
 * @brief Shutdown the XRDeviceProvider
 * @param handle Handle to the XRDeviceProvider instance
 * @return 0: Success, -1: Param error, -2: Other error
 */
VITURE_API int xr_device_provider_shutdown(XRDeviceProviderHandle handle);

/**
 * @brief Destroy the XRDeviceProvider instance
 * @param handle Handle to the XRDeviceProvider instance
 */
VITURE_API void xr_device_provider_destroy(XRDeviceProviderHandle handle);

/**
 * Get core thread IDs, need to be called after start
 * @param handle Handle to the XRDeviceProvider instance
 * @param thread_ids Array to store 2 thread IDs for USB data processing
 * @return 0 on success, -1 on failure
 */
VITURE_API int xr_device_provider_get_thread_id(XRDeviceProviderHandle handle, int thread_ids[2]);

/**
 * @brief Register glass state callback
 * @param handle Handle to the XRDeviceProvider instance
 * @param callback Called when glass state changes
 * @return 0: Success, -1: Param error, -2: USB not available, -3: Other error
 */
VITURE_API int xr_device_provider_register_state_callback(XRDeviceProviderHandle handle, GlassStateCallback callback);

/**
 * @brief Get the device type
 * @param handle Handle to the XRDeviceProvider instance
 * @return XRDeviceType enum value, or -1 on failure
 */
VITURE_API int xr_device_provider_get_device_type(XRDeviceProviderHandle handle);

/**
 * Check if product id is valid
 * @param product_id Product id to check
 * @return Product id is valid or not
 */
VITURE_API bool xr_device_provider_is_product_id_valid(int product_id);

/**
 * Get glasses market name
 * @param product_id Viture product id
 * @param response_data Buffer to store market name
 * @param response_length Pointer to store the length of market name
 */
VITURE_API int xr_device_provider_get_market_name(int product_id, char* market_name, int* length);

/**
 * Set log level
 * @param level 0: No log, 1: Error, 2: Info, 3: Debug
 */
VITURE_API void xr_device_provider_set_log_level(int level);

/**
 * Get log level
 * @return 0: No log, 1: Error, 2: Info, 3: Debug
 */
VITURE_API int xr_device_provider_get_log_level();

/**
 * Set a log hook to capture library log messages
 *
 * When a log hook is set, all log messages will be passed to the callback
 * in addition to the default logging mechanism (Android log or stdio).
 * This allows applications to redirect logs to custom handlers such as:
 * - Remote logging services
 * - Log files
 * - Crash reporting systems
 * - Custom logging frameworks
 *
 * @param hook Callback function to handle log messages. Pass NULL to disable the hook.
 *
 * Example usage:
 * @code
 * void my_log_hook(int level, const char* tag, const char* message) {
 *     // Send to custom logger or file
 *     my_logger_write(level, tag, message);
 * }
 *
 * xr_device_provider_set_log_hook(my_log_hook);
 * @endcode
 */
VITURE_API void xr_device_provider_set_log_hook(LogHook hook);
#ifdef __cplusplus
}
#endif

#endif // VITURE_GLASSES_PROVIDER_H
